-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."MOL"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    fio character varying(50)[] NOT NULL,
    department character(50)[],
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Device"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying(50) NOT NULL,
    inv character varying(50),
    sn character varying(50)[] NOT NULL,
    kab integer NOT NULL,
    data_vvoda date,
    mol integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Job"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    date date NOT NULL,
    "DeviceID" integer NOT NULL,
    type_work character varying(500) NOT NULL,
    note character varying(500),
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Device"
    ADD CONSTRAINT mol FOREIGN KEY (mol)
    REFERENCES public."MOL" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Job"
    ADD CONSTRAINT "DeviceID" FOREIGN KEY ("DeviceID")
    REFERENCES public."Device" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;

END;